### ISSUE TITLE
Can't activate audioplayer sonos option on my NC 21.0.3

### ISSUE THREAD

**Issue by smCloudInTheSky** [Rello/audioplayer_sonos#3]
Hi,

I've installed audioplayer and the sonos plugin. 
In my Admin panel I can't activate the sonos plugin. I got this in the logs when I check the case "enable to all users": 

OCP\AppFramework\QueryException: Could not resolve db! Class db does not exist

Is there a cmd I do have to run on my mysql to resolve this ?
Nextcloud has been installed using the truenas plugin.

Regards

**Comment by Rello** [comment]
Hi,
currently being fixed

**Comment by Rello** [comment]
1.3.0 released
